services:
  database:
    image: redis:7-alpine
    container_name: database
    command:
      - "redis-server"
      - "--port"
      - "0"
      - "--databases"
      - "32"
      - "--appendonly"
      - "no"
      - "--notify-keyspace-events"
      - "KEA"
      - "--unixsocket"
      - "/var/run/redis/redis.sock"
      - "--unixsocketperm"
      - "777"
    volumes:
      - /var/run/redis:/var/run/redis
      - ./database_config.json:/var/run/redis/sonic-db/database_config.json:ro

  runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ows-example-runner
    depends_on:
      - database
    working_dir: /home/ubuntu/ows-example
    volumes:
      - .:/home/ubuntu/ows-example
      - swss-common-install:/usr/local
      - /var/run/redis:/var/run/redis
      - ./database_config.json:/var/run/redis/sonic-db/database_config.json:ro

volumes:
  swss-common-install:
