services:
  database:
    image: redis:7-alpine
    container_name: database
    command:
      - "sh"
      - "-c"
      - |
        mkdir -p /var/run/redis/sonic-db
        chmod 777 /var/run/redis/sonic-db
        exec redis-server /etc/redis/redis.conf
    volumes:
      - /var/run/redis:/var/run/redis
      - ./redis.conf:/etc/redis/redis.conf:ro

  runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: swss-common-example-runner
    depends_on:
      - database
    user: "${UID}:${GID}"
    entrypoint:
      - /bin/bash
      - /home/ubuntu/swss-common-example/entrypoint.sh
    working_dir: /home/ubuntu/swss-common-example
    volumes:
      - .:/home/ubuntu/swss-common-example
      - swss-common-install:/usr/local
      - /var/run/redis:/var/run/redis

volumes:
  swss-common-install:
